name: testing and linting

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Lint
        run: go vet
      - name: Test
        run: go test -v -race ./...
